DECLARE
	CURSOR CC IS 
	SELECT * FROM BRANCH;
	V_CC CC%ROWTYPE;
BEGIN
	OPEN CC;
	LOOP
		FETCH CC INTO V_CC ;
		EXIT WHEN CC %NOTFOUND;
		DBMS_OUTPUT.PUT_LINE('CODE  '||V_CC.CODE  ||' NAME  '||V_CC.NAME  ||'ASSETS  '||V_CC.ASSETS);
	END LOOP;
	CLOSE CC;
END;
/

DECLARE
	CURSOR CC1 IS 
	SELECT * FROM CUSTOMER;
	V_CC1 CC1%ROWTYPE;
BEGIN
	OPEN CC1;
	LOOP
		FETCH CC1 INTO V_CC1;
		EXIT WHEN CC1%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE('SSN  '||V_CC1.SSN  ||' NAME  '||V_CC1.NAME  ||' PLACE  '||V_CC1.PLACE);
	END LOOP;
	CLOSE CC1;
END;
/

DECLARE
	CURSOR CC2 IS 
	SELECT * FROM account;
	V_CC2 CC2%ROWTYPE;
BEGIN
	OPEN CC2;
	LOOP
		FETCH CC2 INTO V_CC2;
		EXIT WHEN CC2%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE('accno  '||V_CC2.accno  ||' ssn  '||V_CC2.ssn  ||' code  '||V_CC2.code ||' balance '||V_CC2.balance);
	END LOOP;
	CLOSE CC2;
END;
/

