CREATE OR REPLACE TRIGGER STOP
BEFORE UPDATE OR DELETE OR INSERT ON EMPLOYEE
FOR EACH ROW
    DECLARE
        E EXCEPTION;
        TODAY DATE:=SYSDATE;
        CURRENT VARCHAR2(20);
    BEGIN
        CURRENT:=TO_CHAR(TODAY,'DAY');
        CURRENT:=RTRIM(CURRENT);
        IF (CURRENT='SUNDAY' OR CURRENT='FRIDAY') THEN
            RAISE E;
        END IF;
    EXCEPTION
        WHEN E THEN
            RAISE_APPLICATION_ERROR( -20500, 'not allowed', FALSE );
    END;
/
